[detector]
enemy_color = "blue"

confidence_threshold = 0.50
nms_threshold = 0.45

min_armor_ratio = 1.0
max_armor_ratio = 6.0
max_rectangular_error = 0.50

enable_debug = false

[inference]
backend = "openvino"
model_path = "data/models/armor.xml"
device = "CPU"
